version: '2'
services:
    hack-app:
        image: hack
        external_links:
            - hack-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/hack
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    hack-postgresql:
        extends:
            file: postgresql.yml
            service: hack-postgresql
